apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS services (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        price DECIMAL(10, 2) NOT NULL,
        tag VARCHAR(50),
        description TEXT
    );

    CREATE TABLE IF NOT EXISTS bookings (
        id SERIAL PRIMARY KEY,
        customer_name VARCHAR(255) NOT NULL,
        phone VARCHAR(50),
        vehicle_model VARCHAR(255) NOT NULL,
        service_id INT REFERENCES services(id),
        status VARCHAR(50) DEFAULT 'Confirmed',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO services (name, price, tag, description) VALUES
    ('Periodic Maintenance', 89.99, 'Popular', 'Engine oil replacement, brake inspection, fluid top-up, and full safety audit.'),
    ('EV & Battery Diagnostics', 149.99, 'Eco Tech', 'High-voltage battery diagnostics, thermal management checks, and electric motor testing.'),
    ('ECU Tuning & Diagnostics', 199.99, 'Advanced', 'Advanced sensor recalibration, firmware updates, and performance tuning.')
    ON CONFLICT DO NOTHING;

    INSERT INTO bookings (customer_name, vehicle_model, service_id, status) VALUES
    ('Nguyen Quang Tung', 'VinFast VF8 Plus', 2, 'In Progress'),
    ('Tran Hoang Nam', 'Porsche Macan GTS', 3, 'Confirmed'),
    ('Le Thi Thu', 'Honda CR-V e:HEV', 1, 'Completed')
    ON CONFLICT DO NOTHING;
