apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: app
type: Opaque
stringData:
  POSTGRES_DB: "autocare_db"
  POSTGRES_USER: "car_admin"
  POSTGRES_PASSWORD: "car_secure_pass_2025"
