apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-serv-backend
  namespace: app
  labels:
    app.kubernetes.io/name: car-serv-backend
    app.kubernetes.io/component: backend-api
    tier: app-tier
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: car-serv-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: car-serv-backend
        app.kubernetes.io/component: backend-api
        tier: app-tier
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      containers:
        - name: backend-api
          image: elroydevops/car-serv-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-api
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: postgres-credentials
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
